### ISSUE TITLE
Add an example

### ISSUE THREAD

**Issue by bjoernQ** [esp-rs/esp-println#29]
While an example wouldn't really help to understand the usage of the library it would make it easier to smoke-test things on PRs

**Comment by brainstorm** [comment]
Totally second that and today I was also wondering if it's possible to output raw bytes to stdout to pipe/redirect I2S mems  microphone data through one of the `esp-hal` examples, i.e:

```sh
$ cargo xtask run-example esp-hal esp32c6 embassy_i2s_read > mic.data
```

On the one hand I suspect this is not the crate to ask about this since print/println's task is to format data, but on the other hand [SO answers like this one](https://www.reddit.com/r/rust/comments/qt3e9f/writing_raw_bytes_to_stdout/) point to `std` (while the embassy and other I2S examples are for `no_std`)... so I guess there should be some kind of primitive in `core` instead for this?

**Comment by MabezDev** [comment]
Hey @brainstorm, swinging by on mobile right now, but generally if you want to write useful bytes (not just logging) out of a uart, you should use the uart in esp-hal, and use the `embedded-io` traits: https://docs.esp-rs.org/esp-hal/esp-hal/0.16.1/esp32s3/esp_hal/uart/struct.Uart.html#method.write_all-1 to do so. `embedded-io` is backed by the embedded working group and is the proper replacement for core io traits :).

**Comment by danclive** [comment]
I tried to add a complete example tonight, but it ended up having reverse dependencies like `esp-hal` and `esp-backtrace`, and I'm not sure how to handle that. Maybe in the future we'll need a dedicated repository, like `esp-examples`, to store more examples.

**Comment by MabezDev** [comment]
@danclive Thanks for looking into this, I think you're right, we'll end up in rev dependency hell if we try and add an example here. Let's close this for now, we already have some usage of `esp_println` in the esp-hal examples anyways.
